# Main config for LEO-CDN Project
# Change this file before you run `make setup`

title = "LEO-CDN Config"

[satellites]
planes = 1
satellites_per_plane = 3

[stardust]
groundstations = 2
requests_per_stardust = 10