# Main config for LEO-CDN Project
# Change this file before you run `make setup`

title = "LEO-CDN Config"

[general]
# Name of the file that contains information about all groundstations.
# File should be located in the `data` folder.
gsts_list = "data/worldcities_5.csv"

[satellites]
# Steps: total amount of required steps for a Satellite to finish a rotation around the globe
# Step_Interval: interval between each step in seconds
# Position_Interval: interval of the position query to the coordinator in seconds

planes = 1
satellites_per_plane = 3
steps = 100
step_interval = 0.25
position_interval = 1
keygroup_layers = 2

[gsts]
# Number of threads that will be created in order to start all GSTs
number_of_threads = 5

["workload"]
interval = 1
output_file = "data/file_orders.json"
num_requests_per_interval = 100
file_size_output_file = "data/file_sizes.csv"
geometric_p = 0.1
pareto_alpha = 1
num_files = 1000
