FROM python:3.8

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./FReD /FReD
ENV PYTHONPATH="${PYTHONPATH}:/FReD"

COPY ./stardust.py /stardust.py
COPY ./proto /proto

CMD ["python", "stardust.py"]
